create schema if not exists extensions;
create extension if not exists postgis with schema extensions;

create schema if not exists private;
revoke all on schema private from public;

create table public.study_area (
  id boolean primary key default true check (id),
  name text not null,
  source text not null,
  geom extensions.geometry(MultiPolygon, 4326) not null,
  constraint study_area_valid_geom check (
    not extensions.st_isempty(geom) and extensions.st_isvalid(geom)
  )
);

create table public.existing_routes (
  id bigint generated by default as identity primary key,
  name text not null,
  route_type text not null check (route_type in ('bus', 'angkot', 'brt', 'other')),
  source text not null,
  geom extensions.geometry(LineString, 4326) not null,
  constraint existing_routes_valid_geom check (
    not extensions.st_isempty(geom) and extensions.st_isvalid(geom)
  )
);

create table public.population_grid (
  id bigint generated by default as identity primary key,
  admin_name text not null,
  population bigint not null check (population >= 0),
  source text not null,
  geom extensions.geometry(MultiPolygon, 4326) not null,
  constraint population_grid_valid_geom check (
    not extensions.st_isempty(geom) and extensions.st_isvalid(geom)
  )
);

create table public.property_go (
  id bigint generated by default as identity primary key,
  kategori text not null,
  jenis text not null check (jenis in ('Sewa', 'Jual')),
  alamat text,
  source text not null,
  geom extensions.geometry(Point, 4326) not null,
  constraint property_go_valid_geom check (
    not extensions.st_isempty(geom) and extensions.st_isvalid(geom)
  )
);

create table public.scoring_config (
  id boolean primary key default true check (id),
  buffer_meters integer not null default 500 check (buffer_meters between 1 and 5000),
  overlap_tolerance_meters integer not null default 100
    check (overlap_tolerance_meters between 1 and 1000),
  population_per_km_target numeric(14, 2) check (population_per_km_target > 0),
  population_weight numeric(4, 3) not null default 0.625
    check (population_weight between 0 and 1),
  overlap_weight numeric(4, 3) not null default 0.375
    check (overlap_weight between 0 and 1),
  constraint scoring_weights_total_one check (population_weight + overlap_weight = 1)
);

insert into public.scoring_config (id) values (true);

create index study_area_geom_idx on public.study_area using gist (geom);
create index existing_routes_geom_idx on public.existing_routes using gist (geom);
create index population_grid_geom_idx on public.population_grid using gist (geom);
create index property_go_geom_idx on public.property_go using gist (geom);

alter table public.study_area enable row level security;
alter table public.existing_routes enable row level security;
alter table public.population_grid enable row level security;
alter table public.property_go enable row level security;
alter table public.scoring_config enable row level security;

revoke all on public.study_area from anon, authenticated;
revoke all on public.existing_routes from anon, authenticated;
revoke all on public.population_grid from anon, authenticated;
revoke all on public.property_go from anon, authenticated;
revoke all on public.scoring_config from anon, authenticated;

create function private.route_from_geojson(p_route jsonb)
returns extensions.geometry
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_route extensions.geometry;
begin
  if p_route is null
    or jsonb_typeof(p_route) <> 'object'
    or p_route ->> 'type' <> 'LineString'
    or jsonb_typeof(p_route -> 'coordinates') <> 'array'
  then
    raise exception 'route must be a GeoJSON LineString' using errcode = '22023';
  end if;

  begin
    v_route := extensions.st_force2d(
      extensions.st_setsrid(extensions.st_geomfromgeojson(p_route::text), 4326)
    );
  exception when others then
    raise exception 'route must contain valid GeoJSON coordinates' using errcode = '22023';
  end;

  if extensions.st_geometrytype(v_route) <> 'ST_LineString'
    or extensions.st_isempty(v_route)
    or not extensions.st_isvalid(v_route)
    or extensions.st_npoints(v_route) < 2
  then
    raise exception 'route must be a non-empty valid LineString' using errcode = '22023';
  end if;

  if extensions.st_npoints(v_route) > 2000 then
    raise exception 'route cannot contain more than 2000 points' using errcode = '22023';
  end if;

  if extensions.st_length(v_route::extensions.geography) < 1
    or extensions.st_length(v_route::extensions.geography) > 200000
  then
    raise exception 'route length must be between 1 metre and 200 kilometres'
      using errcode = '22023';
  end if;

  return v_route;
end;
$$;

create function private.score_route(p_route extensions.geometry)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_config public.scoring_config%rowtype;
  v_study_area extensions.geometry;
  v_buffer extensions.geometry;
  v_existing_corridor extensions.geometry;
  v_route_length_m double precision;
  v_route_length_km double precision;
  v_overlap_length double precision := 0;
  v_population_covered double precision := 0;
  v_population_per_km double precision;
  v_population_score double precision;
  v_overlap_pct double precision := 0;
  v_overlap_score double precision;
  v_composite_score double precision;
  v_property_count integer := 0;
begin
  select * into v_config from public.scoring_config where id = true;
  select geom into v_study_area from public.study_area where id = true;

  if not found or v_study_area is null then
    raise exception 'configure one study_area before evaluating routes' using errcode = '55000';
  end if;
  if v_config.population_per_km_target is null then
    raise exception 'set scoring_config.population_per_km_target after validating study data'
      using errcode = '55000';
  end if;

  v_route_length_m := extensions.st_length(p_route::extensions.geography);
  v_route_length_km := v_route_length_m / 1000.0;
  v_buffer := extensions.st_intersection(
    extensions.st_buffer(
      p_route::extensions.geography,
      v_config.buffer_meters
    )::extensions.geometry,
    v_study_area
  );

  -- ponytail: uniform population inside each polygon; replace the input with a
  -- finer validated grid if this approximation proves too coarse.
  select coalesce(sum(
    pg.population::double precision * least(
      1.0,
      extensions.st_area(
        extensions.st_intersection(pg.geom, v_buffer)::extensions.geography
      ) / nullif(extensions.st_area(pg.geom::extensions.geography), 0)
    )
  ), 0)
  into v_population_covered
  from public.population_grid pg
  where pg.geom operator(extensions.&&) v_buffer
    and extensions.st_intersects(pg.geom, v_buffer);

  select count(*)::integer
  into v_property_count
  from public.property_go pg
  where pg.geom operator(extensions.&&) v_buffer
    and extensions.st_intersects(pg.geom, v_buffer);

  select extensions.st_unaryunion(extensions.st_collect(
    extensions.st_buffer(
      er.geom::extensions.geography,
      v_config.overlap_tolerance_meters
    )::extensions.geometry
  ))
  into v_existing_corridor
  from public.existing_routes er
  where extensions.st_dwithin(
    er.geom::extensions.geography,
    p_route::extensions.geography,
    v_config.overlap_tolerance_meters
  );

  if v_existing_corridor is not null then
    v_overlap_length := coalesce(extensions.st_length(
      extensions.st_intersection(
        p_route::extensions.geography,
        v_existing_corridor::extensions.geography
      )
    ), 0);
  end if;

  v_population_per_km := v_population_covered / v_route_length_km;
  v_population_score := least(
    100.0,
    100.0 * v_population_per_km / v_config.population_per_km_target::double precision
  );
  v_overlap_pct := least(100.0, 100.0 * v_overlap_length / v_route_length_m);
  v_overlap_score := 100.0 - v_overlap_pct;
  v_composite_score :=
    v_population_score * v_config.population_weight::double precision
    + v_overlap_score * v_config.overlap_weight::double precision;

  return jsonb_build_object(
    'score', round(v_composite_score::numeric, 2),
    'route_length_km', round(v_route_length_km::numeric, 2),
    'population_covered', round(v_population_covered)::bigint,
    'population_per_km', round(v_population_per_km::numeric, 2),
    'population_per_km_target', v_config.population_per_km_target,
    'population_score', round(v_population_score::numeric, 2),
    'overlap_pct', round(v_overlap_pct::numeric, 2),
    'overlap_score', round(v_overlap_score::numeric, 2),
    'property_go_count', v_property_count,
    'buffer_geojson', extensions.st_asgeojson(v_buffer, 6)::jsonb,
    'formula', jsonb_build_object(
      'buffer_meters', v_config.buffer_meters,
      'overlap_tolerance_meters', v_config.overlap_tolerance_meters,
      'population_weight', v_config.population_weight,
      'overlap_weight', v_config.overlap_weight,
      'population_assumption', 'uniform_within_polygon'
    )
  );
end;
$$;

create function private.analyze_route(p_route jsonb)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_route extensions.geometry := private.route_from_geojson(p_route);
  v_study_area extensions.geometry;
  v_metric_route extensions.geometry;
  v_candidate extensions.geometry;
  v_best_route extensions.geometry;
  v_baseline jsonb;
  v_candidate_result jsonb;
  v_best_result jsonb;
  v_direction text;
  v_best_direction text;
  v_distance integer;
  v_best_distance integer;
  v_utm_zone integer;
  v_metric_srid integer;
  v_baseline_score numeric;
  v_best_score numeric;
  v_best_population_per_km numeric;
  v_candidate_score numeric;
  v_candidate_population_per_km numeric;
  v_population_delta bigint;
  v_population_per_km_delta numeric;
begin
  select geom into v_study_area from public.study_area where id = true;
  if not found then
    raise exception 'configure one study_area before evaluating routes' using errcode = '55000';
  end if;
  if not extensions.st_coveredby(v_route, v_study_area) then
    raise exception 'route must remain inside the configured study area'
      using errcode = '22023';
  end if;

  v_baseline := private.score_route(v_route);
  v_baseline_score := (v_baseline ->> 'score')::numeric;
  v_best_score := v_baseline_score;
  v_best_population_per_km := (v_baseline ->> 'population_per_km')::numeric;

  v_utm_zone := greatest(1, least(
    60,
    floor((extensions.st_x(extensions.st_centroid(v_route)) + 180) / 6)::integer + 1
  ));
  v_metric_srid := case
    when extensions.st_y(extensions.st_centroid(v_route)) >= 0
      then 32600 + v_utm_zone
    else 32700 + v_utm_zone
  end;
  v_metric_route := extensions.st_transform(v_route, v_metric_srid);

  -- ponytail: fixed 16-candidate search; add more candidates only after an
  -- evaluation demonstrates that the extra database work improves results.
  for v_direction, v_distance in
    select d.value, m.value
    from unnest(array['north', 'south', 'east', 'west']::text[])
      with ordinality as d(value, position)
    cross join unnest(array[300, 500, 800, 1000]::integer[])
      with ordinality as m(value, position)
    order by d.position, m.position
  loop
    v_candidate := extensions.st_transform(
      extensions.st_translate(
        v_metric_route,
        case v_direction
          when 'east' then v_distance
          when 'west' then -v_distance
          else 0
        end,
        case v_direction
          when 'north' then v_distance
          when 'south' then -v_distance
          else 0
        end
      ),
      4326
    );

    continue when not extensions.st_coveredby(v_candidate, v_study_area);

    v_candidate_result := private.score_route(v_candidate);
    v_candidate_score := (v_candidate_result ->> 'score')::numeric;
    v_candidate_population_per_km :=
      (v_candidate_result ->> 'population_per_km')::numeric;

    if v_candidate_score > v_best_score
      or (
        v_candidate_score = v_best_score
        and v_candidate_score > v_baseline_score
        and v_candidate_population_per_km > v_best_population_per_km
      )
      or (
        v_candidate_score = v_best_score
        and v_candidate_population_per_km = v_best_population_per_km
        and v_candidate_score > v_baseline_score
        and v_distance < v_best_distance
      )
    then
      v_best_score := v_candidate_score;
      v_best_population_per_km := v_candidate_population_per_km;
      v_best_route := v_candidate;
      v_best_result := v_candidate_result;
      v_best_direction := v_direction;
      v_best_distance := v_distance;
    end if;
  end loop;

  if v_best_result is null then
    return jsonb_build_object('baseline', v_baseline, 'recommendation', null);
  end if;

  v_population_delta :=
    (v_best_result ->> 'population_covered')::bigint
    - (v_baseline ->> 'population_covered')::bigint;
  v_population_per_km_delta :=
    (v_best_result ->> 'population_per_km')::numeric
    - (v_baseline ->> 'population_per_km')::numeric;

  return jsonb_build_object(
    'baseline', v_baseline,
    'recommendation', jsonb_build_object(
      'direction', v_best_direction,
      'distance_meters', v_best_distance,
      'route_geojson', extensions.st_asgeojson(v_best_route, 6)::jsonb,
      'score_delta', round(v_best_score - v_baseline_score, 2),
      'population_delta', v_population_delta,
      'population_per_km_delta', round(v_population_per_km_delta, 2),
      'result', v_best_result
    )
  );
end;
$$;

create function private.map_context(p_bbox jsonb)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_bbox extensions.geometry;
  v_area public.study_area%rowtype;
  v_existing jsonb;
  v_population jsonb;
  v_properties jsonb;
  v_existing_count bigint;
  v_population_count bigint;
  v_property_count bigint;
begin
  if p_bbox is null
    or jsonb_typeof(p_bbox) <> 'array'
    or jsonb_array_length(p_bbox) <> 4
  then
    raise exception 'bbox must be [west, south, east, north]' using errcode = '22023';
  end if;

  begin
    v_bbox := extensions.st_makeenvelope(
      (p_bbox ->> 0)::double precision,
      (p_bbox ->> 1)::double precision,
      (p_bbox ->> 2)::double precision,
      (p_bbox ->> 3)::double precision,
      4326
    );
  exception when others then
    raise exception 'bbox must contain four valid numbers' using errcode = '22023';
  end;

  select * into v_area from public.study_area where id = true;
  if not found then
    raise exception 'configure one study_area before loading map data' using errcode = '55000';
  end if;

  select count(*) into v_existing_count
  from public.existing_routes where geom operator(extensions.&&) v_bbox;
  select count(*) into v_population_count
  from public.population_grid where geom operator(extensions.&&) v_bbox;
  select count(*) into v_property_count
  from public.property_go where geom operator(extensions.&&) v_bbox;

  select coalesce(jsonb_agg(jsonb_build_object(
    'type', 'Feature',
    'geometry', extensions.st_asgeojson(geom, 6)::jsonb,
    'properties', jsonb_build_object('name', name, 'route_type', route_type)
  )), '[]'::jsonb)
  into v_existing
  from (
    select name, route_type, geom
    from public.existing_routes
    where geom operator(extensions.&&) v_bbox
    order by id
    limit 5000
  ) routes;

  select coalesce(jsonb_agg(jsonb_build_object(
    'type', 'Feature',
    'geometry', extensions.st_asgeojson(
      extensions.st_intersection(geom, v_bbox), 6
    )::jsonb,
    'properties', jsonb_build_object(
      'density_band', case
        when population / nullif(
          extensions.st_area(geom::extensions.geography) / 1000000.0, 0
        ) < 1000 then 'very_low'
        when population / nullif(
          extensions.st_area(geom::extensions.geography) / 1000000.0, 0
        ) < 5000 then 'low'
        when population / nullif(
          extensions.st_area(geom::extensions.geography) / 1000000.0, 0
        ) < 10000 then 'medium'
        when population / nullif(
          extensions.st_area(geom::extensions.geography) / 1000000.0, 0
        ) < 20000 then 'high'
        else 'very_high'
      end
    )
  )), '[]'::jsonb)
  into v_population
  from (
    select population, geom
    from public.population_grid
    where geom operator(extensions.&&) v_bbox
    order by id
    limit 5000
  ) grids;

  select coalesce(jsonb_agg(jsonb_build_object(
    'type', 'Feature',
    'geometry', extensions.st_asgeojson(geom, 6)::jsonb,
    'properties', jsonb_build_object('kategori', kategori)
  )), '[]'::jsonb)
  into v_properties
  from (
    select kategori, geom
    from public.property_go
    where geom operator(extensions.&&) v_bbox
    order by id
    limit 5000
  ) properties;

  return jsonb_build_object(
    'study_area', jsonb_build_object(
      'type', 'Feature',
      'geometry', extensions.st_asgeojson(v_area.geom, 6)::jsonb,
      'properties', jsonb_build_object('name', v_area.name)
    ),
    'existing_routes', jsonb_build_object('type', 'FeatureCollection', 'features', v_existing),
    'population', jsonb_build_object('type', 'FeatureCollection', 'features', v_population),
    'property_go', jsonb_build_object('type', 'FeatureCollection', 'features', v_properties),
    'truncated', jsonb_build_object(
      'existing_routes', v_existing_count > 5000,
      'population', v_population_count > 5000,
      'property_go', v_property_count > 5000
    )
  );
end;
$$;

create function public.analyze_route(p_route jsonb)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select private.analyze_route(p_route);
$$;

create function public.get_map_context(p_bbox jsonb)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select private.map_context(p_bbox);
$$;

revoke all on all functions in schema private from public;
revoke all on function public.analyze_route(jsonb) from public;
revoke all on function public.get_map_context(jsonb) from public;

grant execute on function public.analyze_route(jsonb) to anon, authenticated, service_role;
grant execute on function public.get_map_context(jsonb) to anon, authenticated, service_role;

comment on function public.analyze_route(jsonb) is
  'Scores a GeoJSON LineString and returns the best improving cardinal shift.';
comment on function public.get_map_context(jsonb) is
  'Returns viewport-bounded display-safe GeoJSON without raw population or addresses.';
